#
# Arm GNU Toolchain (GCC)
#
RM = rm -f
ARMGNU ?= arm-none-eabi

CC = $(ARMGNU)-gcc -flto
#								  	bytes/FLTO	Mclks/FLTO
# OPT = -Os -fomit-frame-pointer #	2618	229.00
# OPT = -O1 -fomit-frame-pointer #	3588	119.92
# OPT = -O2 -fomit-frame-pointer #	3412	114.86
OPT = -O3 -fomit-frame-pointer #	3964	100.39
#
# https://www.systemonchips.com/efficient-code-generation-with-gnu-arm-for-cortex-m0-m1/
#
CPU = -mcpu=cortex-m0
OSIZE = -ffunction-sections -fdata-sections -ffreestanding -fno-exceptions -fno-toplevel-reorder -fno-strict-aliasing -fno-common -mno-unaligned-access -funroll-loops
CFLAGS =  -Wall $(CPU) $(OPT) $(OSIZE) -nostdlib -nostartfiles -DUSE_FOR_LOOPS=1
LDFLAGS = -Wl,--print-memory-usage -Wl,--gc-sections #-Wl,--print-gc-sections
MAP = memmap.gnu
SYSOBJS = vectors.o nolib.o nolib_puti.o
LIBS = -lm -lgcc

all : ceforth ceforth33.bin

SRC = ceforth33.c nolib.c nolib_puti.c
OBJ = vectors.o $(SRC:.c=.o)

ceforth.boot : ceforth33.c bootlib.c nolib.h
	cc -Wall -o $@ -DBOOT=1 ceforth33.c bootlib.c

ceforth : dict32le.h ceforth33.c bootlib.c nolib.h
	cc -Wall -DHOSTED=1 -o $@ ceforth33.c bootlib.c

run.hosted: ceforth
	$(RM) run.hosted.log
	./ceforth 2>&1 | tee $@

boot.out: ceforth.boot
	echo bye | ./ceforth.boot > boot.out

dict32le.h: boot.out hex2h.awk
	awk -f hex2h.awk boot.out > $@

vectors.o : vectors.s
	$(ARMGNU)-as $(CPU) vectors.s -o vectors.o

ceforth33.s : ceforth33.c
	$(ARMGNU)-gcc $(CFLAGS) -S -fverbose-asm ceforth33.c

%.elf: %.o $(SYSOBJS) $(MAP)
	$(ARMGNU)-gcc $(CFLAGS) $< $(SYSOBJS) -T $(MAP) -o $@ $(LDFLAGS) $(LIBS)
	$(ARMGNU)-size $@
	$(ARMGNU)-nm --print-size --size-sort --radix=d $@ | tail -10
  
%.bin: %.elf
	$(ARMGNU)-objdump -D $< > $(basename $@).list
	$(ARMGNU)-objdump -t $< > $(basename $@).map
	awk -f symbols.awk $(basename $@).map > $(basename $@).sym
	$(ARMGNU)-objcopy $< $@ -O binary
	ls -l $@

ceforth33.elf : dict32le.h $(OBJ) $(MAP)
	$(ARMGNU)-gcc $(CFLAGS) $(OBJ) -T $(MAP) -o $@ $(LDFLAGS) $(LIBS)
	$(ARMGNU)-size $@
	$(ARMGNU)-nm --print-size --size-sort --radix=d $@ | tail -10

ceforth33.bin : ceforth33.elf
	$(ARMGNU)-objdump -D $< > ceforth33.list
	$(ARMGNU)-objdump -t $< > ceforth33.map
	awk -f symbols.awk ceforth33.map > ceforth33.sym
	$(ARMGNU)-objcopy $< $@ -O binary
	ls -l $@

run: ceforth33.bin
	$(RM) run.log
	../thumbulator -m ceforth33.sym $< 2>&1 | tee run.log

fib: ceforth33.bin fib.f
	cat fib.f | ../thumbulator ceforth33.bin

clean:
	$(RM) *.bin *.o *.elf *.list *.map *.sym
	$(RM) ceforth.boot ceforth dict32le.h boot.out
	$(RM) *.log
	$(RM) -rf *.dSYM
	$(RM) ceforth33.s

# vim:noet :
