#
# Arm Toolchain for Embedded (LLVM)
#
RM = rm -f
TARGET ?= llvm
TCC = clang

OPT = --config=Osize.cfg --config=OmaxLTO.cfg # 2910/2866 123.92/109.46
# OPT = --config=Omax.cfg --config=OmaxLTO.cfg # 3724/3488 FAILS/111.56
#
# https://www.systemonchips.com/efficient-code-generation-with-gnu-arm-for-cortex-m0-m1/
#
CPU = --target=arm-none-eabi -mcpu=cortex-m0
CFLAGS =  $(CPU) -nostdlib $(OPT) -Wall
LDFLAGS = -nostartfiles -Wl,--gc-sections
MAP = memmap.llvm
LIBS = -lclang_rt.builtins -lc
SYSOBJS = vectors.o nolib.o nolib_puti.c

all : ceforth ceforth33.bin

SRCS = ceforth33.c nolib.c
OBJS = $(SRCS:.c=.o)

 
# HOSTED
ceforth.boot : ceforth33.c bootlib.c nolib.h
	cc -Wall -o $@ -DBOOT=1 ceforth33.c bootlib.c

ceforth : dict32le.h ceforth33.c bootlib.c nolib.h
	cc -Wall -DHOSTED=1 -o $@ ceforth33.c bootlib.c

run.hosted: ceforth
	$(RM) run.hosted.log
	./ceforth 2>&1 | tee $@

boot.out: ceforth.boot
	echo bye | ./ceforth.boot > boot.out


# GENERATE IMAGE
dict32le.h: boot.out hex2h.awk
	awk -f hex2h.awk boot.out > $@

vectors.o : vectors.s
	$(TCC) $(CPU) -c vectors.s -o vectors.o

%.o: %.c
	$(TCC) $(CFLAGS) -c $< -o $@

%.bin: %.elf
	$(TARGET)-objcopy $< $@ -O binary
	ls -l $@

%.elf: %.o $(SYSOBJS) $(MAP)
	$(TCC) $(CPU) $(LDFLAGS) $< $(SYSOBJS) -T $(MAP) -o $@ $(LIBS)
	$(TARGET)-size $@
	$(TARGET)-objdump -d $@ > $(basename $@).list
	$(TARGET)-objdump -t $@ > $(basename $@).map
	awk -f symbols.awk $(basename $@).map > $(basename $@).sym

ceforth33.s : dict32le.h ceforth33.c
	$(TCC) $(CFLAGS) -S -fverbose-asm ceforth33.c

run: ceforth33.bin
	$(RM) run.log
	../thumbulator -m ceforth33.sym $< 2>&1 | tee run.log

fib: ceforth33.bin fib.f
	cat fib.f | ../thumbulator ceforth33.bin

clean:
	$(RM) *.bin *.o *.elf *.list *.map *.sym
	$(RM) ceforth.boot ceforth dict32le.h boot.out
	$(RM) *.log
	$(RM) -rf *.dSYM
	$(RM) ceforth33.s

# vim:noet :
# dependencies
ceforth33.o : dict32le.h ceforth33.c
ceforth33.elf : ceforth33.o $(SYSOBJS)

